---
:verbose: false
:concurrency: 2
:timeout: 25

:queues:
  - default

:schedule:
  # status:
  #   class: UpdateServerStatusJob
  #   every: '5m'
  logs:
    class: SyncServerLogsJob
    every: '17m'
