---
regex:
  '\w*n[i1]gg[e3]r\w*': ["discriminatory"]
  '\w*f[a4]gg[o0]t\w*': ["discriminatory"]
  '\w*n[1i]ck ?gurr+\w*': ["discriminatory"]
simple:
  "dyke": ["discriminatory"]
  "fag": ["discriminatory"]
  "fagbag": ["discriminatory"]
  "fagging": ["discriminatory"]
  "fagg": ["discriminatory"]
  "fagot": ["discriminatory"]
  "fagtard": ["discriminatory"]
  "fucktard": ["discriminatory"]
  "kike": ["discriminatory"]
  "kyke": ["discriminatory"]
  "lesbo": ["discriminatory"]
  "lezzie": ["discriminatory"]
  "negro": ["discriminatory"]
  "nig": ["discriminatory"]
  "niglet": ["discriminatory"]
  "kneegrow": ["discriminatory"]
  "tranny": ["discriminatory"]
  "trannies": ["discriminatory"]
  "trannie": ["discriminatory"]
  "tranner": ["discriminatory"]
  "troon": ["discriminatory"]
  "troons": ["discriminatory"]
  "trooner": ["discriminatory"]
  "trender": ["discriminatory"]
  "shemale": ["discriminatory"]
  "wetback": ["discriminatory"]
  "puto": ["discriminatory"]
  "putos": ["discriminatory"]
  "chink": ["discriminatory"]
  "chinks": ["discriminatory"]
  "kys": ["toxic"]
  "kill yourself": ["toxic"]
  "jew": ["toxic"]
  "testalertviora": ["test"]
  "41%": ["discriminatory"]
  "13%": ["discriminatory"]
  "52%": ["discriminatory"]
  "1488": ["toxic"]
  "14/88": ["toxic"]
  "sneed": ["toxic"]
