---
regex:
  'hard ons?\b': ["sexual"]
  'nut\s*sack?\w*': ["sexual"]
  'blow\s*job\w*': ["sexual"]
  'butt\s*plug\w*': ["sexual"]
  'pissed\soff\b': ["inappropriate"]
  '\w*n[i1]gg[e3]r\w*': ["discriminatory"]
  '\w*b[i1]tch\w*': ["insult"]
  '\w*ejaculat\w*': ["sexual"]
  '\w*f[a4]gg[o0]t\w*': ["discriminatory"]
  '\w*wh[o0]r[e3]\w*': ["insult"]
  '\w*p[e3]n[i1]s\w*': ["sexual"]
simple:
  "assbandit": ["discriminatory"]
  "assbanger": ["discriminatory"]
  "assbite": ["insult"]
  "assclown": ["sexual"]
  "asscock": ["insult"]
  "asscracker": ["sexual"]
  "assface": ["sexual"]
  "assgoblin": ["discriminatory"]
  "asshat": ["sexual"]
  "asshead": ["insult"]
  "asshole": ["insult"]
  "asshopper": ["discriminatory"]
  "assjacker": ["discriminatory"]
  "asslick": ["insult"]
  "asslicker": ["insult"]
  "assmonkey": ["insult"]
  "assmunch": ["insult"]
  "assmuncher": ["sexual"]
  "asspirate": ["discriminatory"]
  "assshole": ["sexual"]
  "asssucker": ["insult"]
  "asswad": ["sexual"]
  "asswipe": ["sexual"]
  "bampot": ["insult"]
  "bastard": ["insult"]
  "beaner": ["discriminatory"]
  "beastiality": ["sexual"]
  "beastility": ["sexual"]
  "bestiality": ["sexual"]
  "bullshit": ["inappropriate"]
  "butt-pirate": ["discriminatory"]
  "carpetmuncher": ["discriminatory"]
  "chinc": ["discriminatory"]
  "chink": ["discriminatory"]
  "choad": ["sexual"]
  "chode": ["sexual"]
  "clit": ["sexual"]
  "clitface": ["insult"]
  "cock": ["sexual"]
  "cockbite": ["insult"]
  "cockburger": ["insult"]
  "cockface": ["insult"]
  "cockhead": ["insult"]
  "cockjockey": ["discriminatory"]
  "cockknoker": ["discriminatory"]
  "cockmaster": ["discriminatory"]
  "cockmongler": ["discriminatory"]
  "cockmongruel": ["discriminatory"]
  "cockmonkey": ["insult"]
  "cockmuncher": ["discriminatory"]
  "cocknose": ["insult"]
  "cocknugget": ["insult"]
  "cockshit": ["insult"]
  "cocksmith": ["discriminatory"]
  "cocksmoker": ["discriminatory"]
  "cocksuck": ["sexual", "discriminatory"]
  "cocksucked": ["sexual"]
  "cocksucker": ["discriminatory", "sexual"]
  "cocksucking": ["sexual", "discriminatory"]
  "coochie": ["sexual"]
  "coochy": ["sexual"]
  "coon": ["discriminatory"]
  "cooter": ["sexual"]
  "cumguzzler": ["discriminatory"]
  "cumjockey": ["discriminatory"]
  "cummer": ["sexual"]
  "cumming": ["sexual"]
  "cumshot": ["sexual"]
  "cumslut": ["sexual", "insult"]
  "cumtart": ["insult"]
  "cunillingus": ["sexual"]
  "cunnie": ["sexual"]
  "cunnilingus": ["sexual"]
  "cunt": ["insult", "sexual"]
  "cuntface": ["insult"]
  "cunthole": ["sexual"]
  "cuntlick": ["sexual"]
  "cuntlicker": ["sexual", "discriminatory"]
  "cuntlicking": ["sexual"]
  "cuntrag": ["insult"]
  "dick": ["sexual", "insult"]
  "dickbag": ["insult"]
  "dickbeater": ["sexual"]
  "dickface": ["insult"]
  "dickhead": ["insult"]
  "dickhole": ["sexual"]
  "dickjuice": ["sexual"]
  "dickmilk": ["sexual"]
  "dickmonger": ["discriminatory"]
  "dickslap": ["sexual"]
  "dicksucker": ["discriminatory"]
  "dickwad": ["insult"]
  "dickweasel": ["insult"]
  "dickweed": ["insult"]
  "dickwod": ["insult"]
  "dike": ["discriminatory"]
  "dildo": ["sexual"]
  "dink": ["insult", "sexual"]
  "dipshit": ["insult"]
  "doochbag": ["insult"]
  "dookie": ["inappropriate"]
  "douche": ["insult"]
  "douchebag": ["insult"]
  "dumbshit": ["insult"]
  "dumshit": ["insult"]
  "dyke": ["discriminatory"]
  "fag": ["discriminatory"]
  "fagbag": ["discriminatory"]
  "fagging": ["discriminatory"]
  "faggit": ["discriminatory"]
  "fagg": ["discriminatory"]
  "fagot": ["discriminatory"]
  "fagtard": ["discriminatory"]
  "felatio": ["sexual"]
  "fellatio": ["sexual"]
  "feltch": ["sexual"]
  "flamer": ["discriminatory"]
  "fudgepacker": ["discriminatory"]
  "fucktard": ["discriminatory"]
  "gangbang": ["sexual"]
  "gangbanged": ["sexual"]
  "gayass": ["sexual"]
  "gaybob": ["discriminatory"]
  "gaydo": ["discriminatory"]
  "gaylord": ["discriminatory"]
  "gaysex": ["discriminatory"]
  "gaytard": ["discriminatory"]
  "gaywad": ["discriminatory"]
  "gooch": ["sexual"]
  "gook": ["discriminatory"]
  "gringo": ["discriminatory"]
  "guido": ["discriminatory"]
  "handjob": ["sexual"]
  "heeb": ["discriminatory"]
  "homo": ["discriminatory"]
  "honkey": ["discriminatory"]
  "honky": ["discriminatory"]
  "humping": ["sexual"]
  "jackass": ["insult"]
  "jap": ["discriminatory"]
  "jigaboo": ["discriminatory"]
  "jism": ["sexual"]
  "jiz": ["sexual"]
  "jizm": ["sexual"]
  "jizz": ["sexual"]
  "kike": ["discriminatory"]
  "kock": ["sexual"]
  "kooch": ["sexual"]
  "kootch": ["sexual"]
  "kum": ["sexual"]
  "kumer": ["sexual"]
  "kummer": ["sexual"]
  "kumming": ["sexual"]
  "kunilingus": ["sexual"]
  "kunt": ["sexual"]
  "kyke": ["discriminatory"]
  "lesbo": ["discriminatory"]
  "lezzie": ["discriminatory"]
  "minge": ["sexual"]
  "muff": ["sexual"]
  "muffdiver": ["discriminatory", "sexual"]
  "negro": ["discriminatory"]
  "nigga": ["discriminatory"]
  "niglet": ["discriminatory"]
  "orgasim": ["sexual"]
  "orgasm": ["sexual"]
  "paki": ["discriminatory"]
  "panooch": ["sexual"]
  "pecker": ["sexual"]
  "peckerhead": ["insult"]
  "phonesex": ["sexual"]
  "phuk": ["sexual"]
  "phuked": ["sexual"]
  "phuking": ["sexual"]
  "phukked": ["sexual"]
  "phukking": ["sexual"]
  "phuq": ["sexual"]
  "polesmoker": ["discriminatory"]
  "pollock": ["discriminatory"]
  "poon": ["sexual"]
  "poonani": ["sexual"]
  "poonany": ["sexual"]
  "poontang": ["sexual"]
  "punanny": ["sexual"]
  "pusies": ["sexual", "insult"]
  "pussies": ["sexual", "insult"]
  "pussy": ["sexual", "insult"]
  "pusy": ["sexual"]
  "puto": ["insult"]
  "queef": ["sexual"]
  "queerbait": ["discriminatory"]
  "queerhole": ["discriminatory"]
  "renob": ["sexual"]
  "rimjob": ["sexual"]
  "ruski": ["discriminatory"]
  "retard": ["discriminatory"]
  "retarded": ["discriminatory"]
  "schlong": ["sexual"]
  "scrote": ["sexual"]
  "shitass": ["insult"]
  "shit-ass": ["insult"]
  "shitbag": ["insult"]
  "shit-bag": ["insult"]
  "shitbagger": ["insult"]
  "shit-bagger": ["insult"]
  "shitbrain": ["insult"]
  "shit-brain": ["insult"]
  "shitbreath": ["insult"]
  "shit-breath": ["insult"]
  "shitcunt": ["insult"]
  "shit-cunt": ["insult"]
  "shitdick": ["insult"]
  "shit-dick": ["insult"]
  "shited": ["sexual"]
  "shitface": ["insult"]
  "shit-face": ["insult"]
  "shithead": ["insult"]
  "shit-head": ["insult"]
  "shithole": ["insult"]
  "shiting": ["sexual"]
  "shitspitter": ["sexual"]
  "shit-spitter": ["sexual"]
  "shitstain": ["insult"]
  "shit-stain": ["insult"]
  "skank": ["insult"]
  "skeet": ["sexual"]
  "slut": ["discriminatory"]
  "snatch": ["sexual"]
  "tard": ["discriminatory"]
emoji:
  "1f595": ["insult"]
  "1f4a9": ["inappropriate"]
