---
regex:
  '\w*n[i1]gg[e3]r\w*': ["discriminatory"]
  '\w*f[a4]gg[o0]t\w*': ["discriminatory"]
simple:
  "dyke": ["discriminatory"]
  "fag": ["discriminatory"]
  "fagbag": ["discriminatory"]
  "fagging": ["discriminatory"]
  "fagg": ["discriminatory"]
  "fagot": ["discriminatory"]
  "fagtard": ["discriminatory"]
  "fucktard": ["discriminatory"]
  "kike": ["discriminatory"]
  "kyke": ["discriminatory"]
  "lesbo": ["discriminatory"]
  "lezzie": ["discriminatory"]
  "negro": ["discriminatory"]
  "nigga": ["discriminatory"]
  "niglet": ["discriminatory"]
