name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: chat_log
          POSTGRES_DB: chat_log_test
          POSTGRES_PASSWORD: "foobarbaz"
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://chat_log:foobarbaz@127.0.0.1/chat_log_test"
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rspec
        env:
          DATABASE_URL: "postgres://chat_log:foobarbaz@127.0.0.1/chat_log_test"
          STEAM_WEB_API_KEY: "foobarbaz"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://logs.viora.sh
          environment: production

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'dev.halcyon.hr'
          app-name: 'uncletopia'
          git-push-flags: '--force'

      - name: Update log server
        uses: appleboy/ssh-action@master
        with:
          host: "dev.halcyon.hr"
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL}}
            REDIS_URL: ${{ secrets.REDIS_URL }}
            SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          script_stop: true
          script: |
            docker stop uncletopia.logserver.1
            docker run --rm -d --link dokku.postgres.uncletopia-postgres:dokku-postgres-uncletopia-postgres --link dokku.redis.uncletopia-redis:dokku-redis-uncletopia-redis \
              -e DATABASE_URL \
              -e REDIS_URL \
              -e SECRET_KEY_BASE \
              -e "RAILS_ENV=production" \
              -p 27115:27115/udp \
              --name uncletopia.logserver.1 \
              dokku/uncletopia:latest \
              "/app/bin/rake" "log_server:start"
            sleep 20
            sudo conntrack -D -p udp
            docker image prune -af

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://logs.viora.sh
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://logs.viora.sh
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
